# -*- coding: utf-8 -*-
"""Sample CNN Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18tsT42XVY28d3y8T9yMEtkqNdxfa0pI1
"""

# Create a MobileNetV3Small transfer learning for CIFAR-10

"""### 1. Import Libraries and Device Setup"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms

# Device configuration
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

"""### 2. Load and Prepare CIFAR-10 Dataset"""

# Data transformations
transform_train = transforms.Compose([
    transforms.RandomCrop(32, padding=4),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
])

transform_test = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
])

# CIFAR-10 dataset
trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform_train)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=128, shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform_test)
testloader = torch.utils.data.DataLoader(testset, batch_size=100, shuffle=False, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

"""### 3. Model Definition and Freezing Layers"""

from torchvision.models import mobilenet_v3_small, MobileNet_V3_Small_Weights

# Load pre-trained MobileNetV3Small model
# Using MobileNetV3Small_Weights.IMAGENET1K_V1 for pre-trained weights
model = mobilenet_v3_small(weights=MobileNet_V3_Small_Weights.IMAGENET1K_V1)

# Freeze all parameters in the feature extractor
for param in model.parameters():
    param.requires_grad = False

# Modify the classifier for CIFAR-10 (10 classes)
# The original classifier for MobileNetV3Small is a Sequential block
# The last layer is a Linear layer with 1000 output features
num_ftrs = model.classifier[-1].in_features
model.classifier[-1] = nn.Linear(num_ftrs, len(classes))

model = model.to(device)

print(model)

"""### 4. Loss Function and Optimizer"""

# Define loss function and optimizer
criterion = nn.CrossEntropyLoss()
# Only optimize parameters that are unfrozen (i.e., the new classifier layer)
optimizer = optim.Adam(model.classifier.parameters(), lr=0.001)

"""### 5. Training the Model"""

num_epochs = 10

for epoch in range(num_epochs):
    model.train()  # Set model to training mode
    running_loss = 0.0
    correct_train = 0
    total_train = 0

    for i, data in enumerate(trainloader, 0):
        inputs, labels = data
        inputs, labels = inputs.to(device), labels.to(device)

        optimizer.zero_grad()  # Zero the parameter gradients

        outputs = model(inputs)            # Forward pass
        loss = criterion(outputs, labels)  # Calculate loss
        loss.backward()                    # Backward pass
        optimizer.step()                   # Optimize

        running_loss += loss.item()
        _, predicted = torch.max(outputs.data, 1)
        total_train += labels.size(0)
        correct_train += (predicted == labels).sum().item()

    train_loss = running_loss / len(trainloader)
    train_accuracy = 100 * correct_train / total_train

    # Evaluate on the test set
    model.eval()  # Set model to evaluation mode
    correct_test = 0
    total_test = 0
    test_loss = 0.0
    with torch.no_grad():  # Disable gradient calculation during evaluation
        for data in testloader:
            images, labels = data
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            loss = criterion(outputs, labels)
            test_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            total_test += labels.size(0)
            correct_test += (predicted == labels).sum().item()

    test_loss /= len(testloader)
    test_accuracy = 100 * correct_test / total_test

    print(f'Epoch [{epoch+1}/{num_epochs}], '
          f'Train Loss: {train_loss:.4f}, Train Acc: {train_accuracy:.2f}%, '
          f'Test Loss: {test_loss:.4f}, Test Acc: {test_accuracy:.2f}%')

print('\nFinished Training')

scripted_model = torch.jit.script(model)
scripted_model.save("scripted_model.pt")

from google.colab import drive
drive.mount('/content/drive')